import { PrismaClient } from '@prisma/client'
import bcrypt from 'bcryptjs'

const prisma = new PrismaClient()

async function main() {
  console.log('🌱 Seeding database with jobs...')

  // Create employer user
  const hashedPassword = await bcrypt.hash('password123', 10)
  
  const employer = await prisma.user.upsert({
    where: { email: 'employer@oceanic.job' },
    update: {},
    create: {
      email: 'employer@oceanic.job',
      name: 'OceanicJob Recruiter',
      password: hashedPassword,
      role: 'EMPLOYER',
    }
  })

  console.log('✅ Created employer:', employer.email)

  // Create companies
  const companies = [
    {
      name: 'TechVision Labs',
      description: 'Leader en solutions d\'IA et machine learning pour l\'industrie',
      website: 'https://techvision.io',
      industry: 'Technology',
      size: '50-200',
      location: 'Paris, France',
    },
    {
      name: 'GreenEnergy Solutions',
      description: 'Pionnier des énergies renouvelables et solutions durables',
      website: 'https://greenenergy.fr',
      industry: 'Energy',
      size: '200-500',
      location: 'Lyon, France',
    },
    {
      name: 'FinTech Innovations',
      description: 'Startup fintech révolutionnant les paiements numériques',
      website: 'https://fintechinno.com',
      industry: 'Finance',
      size: '10-50',
      location: 'Bordeaux, France',
    },
    {
      name: 'HealthCare Plus',
      description: 'Solutions de santé connectée et télémédecine',
      website: 'https://healthcareplus.fr',
      industry: 'Healthcare',
      size: '100-200',
      location: 'Marseille, France',
    },
  ]

  const createdCompanies = []
  for (const company of companies) {
    const created = await prisma.company.upsert({
      where: { id: `company-${company.name.toLowerCase().replace(/\s/g, '-')}` },
      update: {},
      create: {
        id: `company-${company.name.toLowerCase().replace(/\s/g, '-')}`,
        ...company,
        employerId: employer.id,
      }
    })
    createdCompanies.push(created)
    console.log('✅ Created company:', created.name)
  }

  // Job listings
  const jobs = [
    {
      title: 'Développeur Full Stack Senior',
      description: 'Nous recherchons un développeur Full Stack expérimenté pour rejoindre notre équipe technique. Vous travaillerez sur des projets innovants utilisant les dernières technologies.',
      category: 'technology',
      location: 'Paris, France',
      locationType: 'hybrid',
      employmentType: 'full-time',
      experienceLevel: 'senior',
      salaryMin: 55000,
      salaryMax: 75000,
      salaryCurrency: 'EUR',
      salaryPeriod: 'yearly',
      requirements: JSON.stringify(['5+ ans d\'expérience en développement web', 'Maîtrise de React, Node.js, TypeScript', 'Expérience avec les bases de données SQL et NoSQL', 'Bonnes compétences en communication']),
      responsibilities: JSON.stringify(['Développer des fonctionnalités front-end et back-end', 'Participer aux code reviews', 'Mentorer les développeurs juniors', 'Contribuer à l\'architecture technique']),
      benefits: JSON.stringify(['Télétravail flexible', 'Mutuelle premium', 'RTT', 'Tickets restaurant']),
      companyId: createdCompanies[0].id,
    },
    {
      title: 'Data Scientist',
      description: 'Rejoignez notre équipe Data pour analyser et exploiter nos données massives. Vous développerez des modèles de machine learning innovants.',
      category: 'technology',
      location: 'Paris, France',
      locationType: 'remote',
      employmentType: 'full-time',
      experienceLevel: 'mid',
      salaryMin: 45000,
      salaryMax: 60000,
      salaryCurrency: 'EUR',
      salaryPeriod: 'yearly',
      requirements: JSON.stringify(['3+ ans en Data Science', 'Python, TensorFlow/PyTorch', 'SQL avancé', 'Master en statistiques ou équivalent']),
      responsibilities: JSON.stringify(['Développer des modèles ML', 'Analyser les données business', 'Présenter les insights aux équipes', 'Optimiser les pipelines de données']),
      benefits: JSON.stringify(['100% remote', 'Formation continue', 'Stock options', 'Équipement fourni']),
      companyId: createdCompanies[0].id,
    },
    {
      title: 'Ingénieur DevOps',
      description: 'Nous cherchons un ingénieur DevOps pour automatiser et optimiser notre infrastructure cloud.',
      category: 'engineering',
      location: 'Lyon, France',
      locationType: 'hybrid',
      employmentType: 'full-time',
      experienceLevel: 'senior',
      salaryMin: 50000,
      salaryMax: 70000,
      salaryCurrency: 'EUR',
      salaryPeriod: 'yearly',
      requirements: JSON.stringify(['5+ ans en DevOps/SRE', 'AWS ou GCP certifié', 'Kubernetes, Docker, Terraform', 'CI/CD pipelines']),
      responsibilities: JSON.stringify(['Gérer l\'infrastructure cloud', 'Automatiser les déploiements', 'Monitorer les systèmes', 'Améliorer la sécurité']),
      benefits: JSON.stringify(['Télétravail 3j/semaine', 'Prime annuelle', 'Conférences payées', 'Mutuelle famille']),
      companyId: createdCompanies[1].id,
    },
    {
      title: 'Chef de Projet Digital',
      description: 'Pilotez des projets digitaux innovants pour nos clients grands comptes.',
      category: 'product',
      location: 'Paris, France',
      locationType: 'onsite',
      employmentType: 'full-time',
      experienceLevel: 'lead',
      salaryMin: 55000,
      salaryMax: 75000,
      salaryCurrency: 'EUR',
      salaryPeriod: 'yearly',
      requirements: JSON.stringify(['7+ ans en gestion de projet', 'Certification PMP ou Prince2', 'Expérience Agile/Scrum', 'Excellent relationnel client']),
      responsibilities: JSON.stringify(['Piloter les projets de A à Z', 'Gérer les équipes projet', 'Assurer la relation client', 'Garantir les délais et budgets']),
      benefits: JSON.stringify(['Véhicule de fonction', 'Bonus performance', 'Formation management', 'Séminaires annuels']),
      companyId: createdCompanies[0].id,
    },
    {
      title: 'UX/UI Designer',
      description: 'Créez des expériences utilisateur exceptionnelles pour nos applications web et mobile.',
      category: 'design',
      location: 'Bordeaux, France',
      locationType: 'hybrid',
      employmentType: 'full-time',
      experienceLevel: 'mid',
      salaryMin: 38000,
      salaryMax: 50000,
      salaryCurrency: 'EUR',
      salaryPeriod: 'yearly',
      requirements: JSON.stringify(['3+ ans en UX/UI Design', 'Maîtrise Figma, Adobe XD', 'Portfolio solide', 'Connaissance des guidelines iOS/Android']),
      responsibilities: JSON.stringify(['Créer des maquettes et prototypes', 'Conduire des tests utilisateurs', 'Définir les guidelines UI', 'Collaborer avec les développeurs']),
      benefits: JSON.stringify(['Macbook Pro', 'Abonnement design tools', 'Horaires flexibles', 'Team building mensuel']),
      companyId: createdCompanies[2].id,
    },
    {
      title: 'Développeur Mobile React Native',
      description: 'Développez des applications mobiles cross-platform performantes.',
      category: 'technology',
      location: 'Lille, France',
      locationType: 'remote',
      employmentType: 'full-time',
      experienceLevel: 'mid',
      salaryMin: 42000,
      salaryMax: 55000,
      salaryCurrency: 'EUR',
      salaryPeriod: 'yearly',
      requirements: JSON.stringify(['3+ ans React Native', 'TypeScript', 'Publication sur stores', 'Tests automatisés']),
      responsibilities: JSON.stringify(['Développer des features mobile', 'Optimiser les performances', 'Gérer les releases', 'Code reviews']),
      benefits: JSON.stringify(['Full remote', 'Budget équipement', 'Conférences', 'Flexibilité horaire']),
      companyId: createdCompanies[0].id,
    },
    {
      title: 'Ingénieur Énergies Renouvelables',
      description: 'Participez à la transition énergétique en concevant des solutions solaires innovantes.',
      category: 'engineering',
      location: 'Lyon, France',
      locationType: 'onsite',
      employmentType: 'full-time',
      experienceLevel: 'mid',
      salaryMin: 40000,
      salaryMax: 55000,
      salaryCurrency: 'EUR',
      salaryPeriod: 'yearly',
      requirements: JSON.stringify(['Diplôme ingénieur énergie', '3+ ans dans le solaire/éolien', 'Connaissances réglementaires', 'Logiciels de simulation']),
      responsibilities: JSON.stringify(['Concevoir des installations', 'Suivre les chantiers', 'Rédiger les études techniques', 'Former les équipes terrain']),
      benefits: JSON.stringify(['Véhicule de service', 'Prime projet', 'RTT', 'Intéressement']),
      companyId: createdCompanies[1].id,
    },
    {
      title: 'Commercial B2B',
      description: 'Développez notre portefeuille clients entreprises dans le secteur énergétique.',
      category: 'sales',
      location: 'Toulouse, France',
      locationType: 'hybrid',
      employmentType: 'full-time',
      experienceLevel: 'mid',
      salaryMin: 35000,
      salaryMax: 50000,
      salaryCurrency: 'EUR',
      salaryPeriod: 'yearly',
      requirements: JSON.stringify(['3+ ans en vente B2B', 'Connaissance du secteur énergie', 'Permis B', 'CRM Salesforce']),
      responsibilities: JSON.stringify(['Prospecter de nouveaux clients', 'Négocier les contrats', 'Atteindre les objectifs de vente', 'Fidéliser les clients existants']),
      benefits: JSON.stringify(['Commissions non plafonnées', 'Voiture de fonction', 'Téléphone pro', 'Séminaires annuels']),
      companyId: createdCompanies[1].id,
    },
    {
      title: 'Analyste Financier',
      description: 'Analysez les performances financières et contribuez aux décisions stratégiques.',
      category: 'finance',
      location: 'Paris, France',
      locationType: 'onsite',
      employmentType: 'full-time',
      experienceLevel: 'entry',
      salaryMin: 35000,
      salaryMax: 45000,
      salaryCurrency: 'EUR',
      salaryPeriod: 'yearly',
      requirements: JSON.stringify(['Master Finance/Comptabilité', 'Excel avancé', 'Anglais courant', 'Connaissances comptables']),
      responsibilities: JSON.stringify(['Analyser les états financiers', 'Préparer les reportings', 'Suivre les KPIs', 'Participer aux clôtures']),
      benefits: JSON.stringify(['Formation CFA sponsorisée', 'Bonus annuel', 'Télétravail 1j/sem', 'Mutuelle']),
      companyId: createdCompanies[2].id,
    },
    {
      title: 'Responsable Marketing Digital',
      description: 'Définissez et exécutez la stratégie marketing digitale de notre startup fintech.',
      category: 'marketing',
      location: 'Bordeaux, France',
      locationType: 'hybrid',
      employmentType: 'full-time',
      experienceLevel: 'senior',
      salaryMin: 50000,
      salaryMax: 65000,
      salaryCurrency: 'EUR',
      salaryPeriod: 'yearly',
      requirements: JSON.stringify(['5+ ans en marketing digital', 'Expérience startup/fintech', 'Google Ads, Meta Ads', 'Analytics & data-driven']),
      responsibilities: JSON.stringify(['Définir la stratégie marketing', 'Gérer le budget acquisition', 'Manager l\'équipe marketing', 'Optimiser les conversions']),
      benefits: JSON.stringify(['Stock options', 'Budget formation illimité', 'Télétravail flexible', 'Afterworks']),
      companyId: createdCompanies[2].id,
    },
    {
      title: 'Développeur Backend Python',
      description: 'Construisez des APIs robustes et scalables pour notre plateforme de paiement.',
      category: 'technology',
      location: 'Paris, France',
      locationType: 'remote',
      employmentType: 'full-time',
      experienceLevel: 'mid',
      salaryMin: 45000,
      salaryMax: 60000,
      salaryCurrency: 'EUR',
      salaryPeriod: 'yearly',
      requirements: JSON.stringify(['4+ ans Python', 'Django/FastAPI', 'PostgreSQL', 'Architecture microservices']),
      responsibilities: JSON.stringify(['Développer des APIs REST', 'Optimiser les performances', 'Écrire des tests', 'Documenter le code']),
      benefits: JSON.stringify(['Full remote', 'Équipement premium', 'Conférences', '13ème mois']),
      companyId: createdCompanies[2].id,
    },
    {
      title: 'Médecin Téléconsultant',
      description: 'Exercez la médecine à distance via notre plateforme de télémédecine innovante.',
      category: 'other',
      location: 'France (Remote)',
      locationType: 'remote',
      employmentType: 'part-time',
      experienceLevel: 'mid',
      salaryMin: 80,
      salaryMax: 120,
      salaryCurrency: 'EUR',
      salaryPeriod: 'monthly',
      requirements: JSON.stringify(['Doctorat en médecine', 'Inscription à l\'Ordre', '3+ ans d\'expérience', 'Aisance avec les outils numériques']),
      responsibilities: JSON.stringify(['Réaliser des téléconsultations', 'Rédiger des ordonnances', 'Orienter les patients', 'Participer aux gardes']),
      benefits: JSON.stringify(['Horaires flexibles', 'Plateforme ergonomique', 'Formation continue', 'Prime de disponibilité']),
      companyId: createdCompanies[3].id,
    },
    {
      title: 'Infirmier(ère) Coordinateur(trice)',
      description: 'Coordonnez les parcours de soins des patients en télémédecine.',
      category: 'other',
      location: 'Marseille, France',
      locationType: 'hybrid',
      employmentType: 'full-time',
      experienceLevel: 'mid',
      salaryMin: 32000,
      salaryMax: 40000,
      salaryCurrency: 'EUR',
      salaryPeriod: 'yearly',
      requirements: JSON.stringify(['Diplôme d\'État Infirmier', '3+ ans d\'expérience', 'Sens de l\'organisation', 'Empathie et écoute']),
      responsibilities: JSON.stringify(['Coordonner les soins', 'Suivre les patients', 'Former les équipes', 'Gérer les plannings']),
      benefits: JSON.stringify(['Primes', 'Formation continue', 'Mutuelle complète', 'Congés supplémentaires']),
      companyId: createdCompanies[3].id,
    },
    {
      title: 'Stage Développeur Web',
      description: 'Rejoignez notre équipe tech pour un stage de 6 mois avec possibilité d\'embauche.',
      category: 'technology',
      location: 'Paris, France',
      locationType: 'hybrid',
      employmentType: 'internship',
      experienceLevel: 'entry',
      salaryMin: 1200,
      salaryMax: 1500,
      salaryCurrency: 'EUR',
      salaryPeriod: 'monthly',
      requirements: JSON.stringify(['Bac+4/5 en informatique', 'Connaissances HTML/CSS/JS', 'Curiosité et motivation', 'Travail en équipe']),
      responsibilities: JSON.stringify(['Développer des fonctionnalités', 'Corriger des bugs', 'Participer aux sprints', 'Apprendre les bonnes pratiques']),
      benefits: JSON.stringify(['Mentorat personnalisé', 'Tickets restaurant', 'Transports remboursés', 'Possibilité CDI']),
      companyId: createdCompanies[0].id,
    },
    {
      title: 'Product Owner',
      description: 'Définissez la vision produit et priorisez le backlog de notre application phare.',
      category: 'product',
      location: 'Nantes, France',
      locationType: 'hybrid',
      employmentType: 'full-time',
      experienceLevel: 'senior',
      salaryMin: 50000,
      salaryMax: 70000,
      salaryCurrency: 'EUR',
      salaryPeriod: 'yearly',
      requirements: JSON.stringify(['5+ ans en Product Management', 'Certification PSPO', 'Expérience Agile', 'Background tech apprécié']),
      responsibilities: JSON.stringify(['Définir la roadmap', 'Prioriser le backlog', 'Collaborer avec les devs', 'Analyser les métriques']),
      benefits: JSON.stringify(['Télétravail 3j/sem', 'Conférences produit', 'Stock options', 'Team retreats']),
      companyId: createdCompanies[2].id,
    },
    {
      title: 'Responsable RH',
      description: 'Gérez les ressources humaines de notre entreprise en pleine croissance.',
      category: 'hr',
      location: 'Lyon, France',
      locationType: 'onsite',
      employmentType: 'full-time',
      experienceLevel: 'senior',
      salaryMin: 45000,
      salaryMax: 60000,
      salaryCurrency: 'EUR',
      salaryPeriod: 'yearly',
      requirements: JSON.stringify(['Master RH', '5+ ans en RH généraliste', 'Droit du travail', 'SIRH (Workday, SAP)']),
      responsibilities: JSON.stringify(['Gérer les recrutements', 'Administrer la paie', 'Développer les talents', 'Gérer les relations sociales']),
      benefits: JSON.stringify(['13ème mois', 'Mutuelle famille', 'RTT', 'Formation continue']),
      companyId: createdCompanies[1].id,
    },
    {
      title: 'Customer Success Manager',
      description: 'Accompagnez nos clients dans l\'adoption et l\'utilisation de notre solution.',
      category: 'support',
      location: 'Paris, France',
      locationType: 'hybrid',
      employmentType: 'full-time',
      experienceLevel: 'mid',
      salaryMin: 40000,
      salaryMax: 55000,
      salaryCurrency: 'EUR',
      salaryPeriod: 'yearly',
      requirements: JSON.stringify(['3+ ans en CSM/Account Management', 'Anglais courant', 'Outils CRM', 'Orientation client forte']),
      responsibilities: JSON.stringify(['Onboarder les nouveaux clients', 'Suivre la satisfaction', 'Upsell et cross-sell', 'Gérer les escalades']),
      benefits: JSON.stringify(['Bonus trimestriel', 'Télétravail flexible', 'Afterworks', 'Voyages clients']),
      companyId: createdCompanies[0].id,
    },
    {
      title: 'Juriste Droit des Affaires',
      description: 'Apportez votre expertise juridique à notre équipe légale en croissance.',
      category: 'legal',
      location: 'Paris, France',
      locationType: 'onsite',
      employmentType: 'full-time',
      experienceLevel: 'mid',
      salaryMin: 45000,
      salaryMax: 60000,
      salaryCurrency: 'EUR',
      salaryPeriod: 'yearly',
      requirements: JSON.stringify(['Master 2 Droit des affaires', '3+ ans en cabinet ou entreprise', 'Anglais juridique', 'Contrats tech/IT']),
      responsibilities: JSON.stringify(['Rédiger et négocier les contrats', 'Conseiller les équipes', 'Gérer les contentieux', 'Veille juridique']),
      benefits: JSON.stringify(['Cabinet d\'avocats partenaire', 'Formation continue', 'Télétravail 2j/sem', 'Mutuelle premium']),
      companyId: createdCompanies[2].id,
    },
    {
      title: 'Technicien Support IT',
      description: 'Assurez le support technique de premier niveau pour nos utilisateurs internes.',
      category: 'support',
      location: 'Marseille, France',
      locationType: 'onsite',
      employmentType: 'full-time',
      experienceLevel: 'entry',
      salaryMin: 28000,
      salaryMax: 35000,
      salaryCurrency: 'EUR',
      salaryPeriod: 'yearly',
      requirements: JSON.stringify(['Bac+2 Informatique', 'Connaissances Windows/Mac', 'Notions réseau', 'Sens du service']),
      responsibilities: JSON.stringify(['Résoudre les tickets', 'Installer les postes', 'Gérer le parc informatique', 'Documenter les procédures']),
      benefits: JSON.stringify(['Tickets restaurant', 'Mutuelle', 'Formation technique', 'Évolution possible']),
      companyId: createdCompanies[3].id,
    },
  ]

  // Create all jobs
  for (const job of jobs) {
    await prisma.job.create({
      data: {
        ...job,
        status: 'OPEN',
      }
    })
    console.log('✅ Created job:', job.title)
  }

  console.log(`\n🎉 Successfully seeded ${jobs.length} jobs!`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
