import { PrismaClient } from '@prisma/client'
import bcrypt from 'bcryptjs'

const prisma = new PrismaClient()

async function main() {
  console.log('🌱 Seeding database with Madagascar remote jobs...')

  // Create employer user
  const hashedPassword = await bcrypt.hash('password123', 10)
  
  const employer = await prisma.user.upsert({
    where: { email: 'employer@oceanic.job' },
    update: {},
    create: {
      email: 'employer@oceanic.job',
      name: 'OceanicJob Recruiter',
      password: hashedPassword,
      role: 'EMPLOYER',
    }
  })

  console.log('✅ Created employer:', employer.email)

  // French companies that outsource to Madagascar
  const companies = [
    {
      name: 'Webhelp Madagascar',
      description: 'Leader européen de l\'expérience client et de l\'externalisation BPO. Présent à Madagascar depuis 2008, nous offrons des opportunités de carrière internationales.',
      website: 'https://webhelp.com',
      industry: 'BPO & Customer Service',
      size: '1000+',
      location: 'Antananarivo, Madagascar',
      logo: null,
    },
    {
      name: 'Intelcia Madagascar',
      description: 'Groupe français spécialisé dans la relation client et les solutions digitales. Nous accompagnons les entreprises françaises dans leur transformation digitale.',
      website: 'https://intelcia.com',
      industry: 'BPO & Customer Service',
      size: '500-1000',
      location: 'Antananarivo, Madagascar',
      logo: null,
    },
    {
      name: 'Vivetic Group',
      description: 'Spécialiste français du traitement de données et de la modération de contenu. Notre centre à Madagascar emploie des experts en data entry et analyse.',
      website: 'https://vivetic.com',
      industry: 'Data Processing',
      size: '200-500',
      location: 'Antananarivo, Madagascar',
      logo: null,
    },
    {
      name: 'Bocasay',
      description: 'ESN française spécialisée dans le développement offshore. Nous créons des applications web et mobile pour des clients européens depuis Madagascar.',
      website: 'https://bocasay.com',
      industry: 'Technology',
      size: '100-200',
      location: 'Antananarivo, Madagascar',
      logo: null,
    },
    {
      name: 'Activ Digital',
      description: 'Agence digitale française avec une équipe créative à Madagascar. Nous offrons des services de design, développement web et marketing digital.',
      website: 'https://activdigital.mg',
      industry: 'Digital Agency',
      size: '50-100',
      location: 'Antananarivo, Madagascar',
      logo: null,
    },
    {
      name: 'E-Trésorier',
      description: 'Cabinet comptable français innovant utilisant le cloud et l\'externalisation pour offrir des services de comptabilité de qualité à prix compétitif.',
      website: 'https://e-tresorier.fr',
      industry: 'Finance & Accounting',
      size: '50-100',
      location: 'Antananarivo, Madagascar',
      logo: null,
    },
    {
      name: 'Mediakeys',
      description: 'Groupe média français spécialisé dans la publicité digitale. Notre hub malgache gère les campagnes et l\'analyse de données pour des marques internationales.',
      website: 'https://mediakeys.com',
      industry: 'Marketing & Advertising',
      size: '100-200',
      location: 'Antananarivo, Madagascar',
      logo: null,
    },
    {
      name: 'Assureo',
      description: 'Courtier d\'assurance français digitalisant ses processus. Nous recherchons des talents malgaches pour la gestion de contrats et le support client.',
      website: 'https://assureo.fr',
      industry: 'Insurance',
      size: '50-100',
      location: 'Antananarivo, Madagascar',
      logo: null,
    },
  ]

  const createdCompanies = []
  for (const company of companies) {
    const created = await prisma.company.upsert({
      where: { id: `company-${company.name.toLowerCase().replace(/\s/g, '-')}` },
      update: {},
      create: {
        id: `company-${company.name.toLowerCase().replace(/\s/g, '-')}`,
        ...company,
        employerId: employer.id,
      }
    })
    createdCompanies.push(created)
    console.log('✅ Created company:', created.name)
  }

  // Job listings - Common remote jobs in Madagascar for French companies
  const jobs = [
    // === CUSTOMER SERVICE / CALL CENTER ===
    {
      title: 'Téléconseiller Bilingue Français',
      description: 'Rejoignez notre équipe de service client et accompagnez les clients français dans leurs demandes. Formation complète assurée, ambiance de travail dynamique.',
      category: 'support',
      location: 'Antananarivo, Madagascar',
      locationType: 'onsite',
      employmentType: 'full-time',
      experienceLevel: 'entry',
      salaryMin: 500000,
      salaryMax: 800000,
      salaryCurrency: 'MGA',
      salaryPeriod: 'monthly',
      requirements: JSON.stringify(['Français courant (niveau C1 minimum)', 'Bac+2 ou équivalent', 'Bonne élocution', 'Maîtrise des outils informatiques']),
      responsibilities: JSON.stringify(['Répondre aux appels entrants des clients', 'Traiter les réclamations et demandes', 'Saisir les informations dans le CRM', 'Atteindre les objectifs qualité']),
      benefits: JSON.stringify(['Transport assuré', 'Prime de performance', 'Mutuelle santé', 'Formation continue']),
      companyId: createdCompanies[0].id,
    },
    {
      title: 'Chargé(e) de Clientèle - Secteur Assurance',
      description: 'Gérez un portefeuille de clients assurance en France. Vous assurez le suivi des contrats et le conseil personnalisé par téléphone et email.',
      category: 'support',
      location: 'Antananarivo, Madagascar',
      locationType: 'onsite',
      employmentType: 'full-time',
      experienceLevel: 'entry',
      salaryMin: 600000,
      salaryMax: 900000,
      salaryCurrency: 'MGA',
      salaryPeriod: 'monthly',
      requirements: JSON.stringify(['Français impeccable', 'Expérience en relation client appréciée', 'Connaissance du secteur assurance est un plus', 'Sens commercial']),
      responsibilities: JSON.stringify(['Gérer les demandes clients par téléphone', 'Conseiller sur les produits d\'assurance', 'Traiter les modifications de contrats', 'Fidéliser les clients']),
      benefits: JSON.stringify(['Horaires de bureau français', 'Primes mensuelles', 'Évolution de carrière', 'Environnement international']),
      companyId: createdCompanies[7].id,
    },
    {
      title: 'Superviseur Centre d\'appels',
      description: 'Encadrez une équipe de téléconseillers et assurez l\'atteinte des objectifs de performance. Poste de management avec perspectives d\'évolution.',
      category: 'support',
      location: 'Antananarivo, Madagascar',
      locationType: 'onsite',
      employmentType: 'full-time',
      experienceLevel: 'mid',
      salaryMin: 1200000,
      salaryMax: 1800000,
      salaryCurrency: 'MGA',
      salaryPeriod: 'monthly',
      requirements: JSON.stringify(['2+ ans en centre d\'appels', 'Expérience en management d\'équipe', 'Maîtrise des KPIs relation client', 'Leadership et communication']),
      responsibilities: JSON.stringify(['Manager une équipe de 15-20 téléconseillers', 'Suivre les indicateurs de performance', 'Coacher et former les agents', 'Reporting à la direction']),
      benefits: JSON.stringify(['Salaire attractif', 'Bonus sur objectifs', 'Mutuelle premium', 'Plan de carrière']),
      companyId: createdCompanies[1].id,
    },

    // === DATA ENTRY / BACK OFFICE ===
    {
      title: 'Opérateur(trice) de Saisie',
      description: 'Effectuez la saisie et le traitement de données pour des clients français. Poste idéal pour démarrer une carrière dans le digital.',
      category: 'other',
      location: 'Antananarivo, Madagascar',
      locationType: 'onsite',
      employmentType: 'full-time',
      experienceLevel: 'entry',
      salaryMin: 400000,
      salaryMax: 600000,
      salaryCurrency: 'MGA',
      salaryPeriod: 'monthly',
      requirements: JSON.stringify(['Maîtrise du clavier (frappe rapide)', 'Rigueur et attention aux détails', 'Maîtrise de Word et Excel', 'Niveau bac minimum']),
      responsibilities: JSON.stringify(['Saisir des données dans les systèmes', 'Vérifier la qualité des informations', 'Respecter les délais de traitement', 'Archiver les documents numériques']),
      benefits: JSON.stringify(['Formation assurée', 'Transport pris en charge', 'Heures supplémentaires payées', 'Évolution possible']),
      companyId: createdCompanies[2].id,
    },
    {
      title: 'Gestionnaire Back-Office Bancaire',
      description: 'Traitez les opérations back-office pour une banque française. Poste nécessitant rigueur et confidentialité.',
      category: 'finance',
      location: 'Antananarivo, Madagascar',
      locationType: 'onsite',
      employmentType: 'full-time',
      experienceLevel: 'entry',
      salaryMin: 700000,
      salaryMax: 1000000,
      salaryCurrency: 'MGA',
      salaryPeriod: 'monthly',
      requirements: JSON.stringify(['Bac+2 en gestion, comptabilité ou banque', 'Français courant', 'Maîtrise d\'Excel', 'Discrétion professionnelle']),
      responsibilities: JSON.stringify(['Traiter les opérations bancaires', 'Vérifier les documents clients', 'Mettre à jour les dossiers', 'Respecter les procédures de conformité']),
      benefits: JSON.stringify(['Salaire compétitif', 'Formation bancaire', 'Mutuelle', 'Prime annuelle']),
      companyId: createdCompanies[2].id,
    },
    {
      title: 'Modérateur(trice) de Contenu',
      description: 'Modérez le contenu sur les plateformes de nos clients (réseaux sociaux, sites web). Vous garantissez le respect des guidelines.',
      category: 'other',
      location: 'Antananarivo, Madagascar',
      locationType: 'onsite',
      employmentType: 'full-time',
      experienceLevel: 'entry',
      salaryMin: 500000,
      salaryMax: 750000,
      salaryCurrency: 'MGA',
      salaryPeriod: 'monthly',
      requirements: JSON.stringify(['Français et/ou anglais courant', 'Connaissance des réseaux sociaux', 'Capacité à gérer le contenu sensible', 'Jugement rapide et objectif']),
      responsibilities: JSON.stringify(['Examiner le contenu signalé', 'Appliquer les règles de modération', 'Escalader les cas complexes', 'Contribuer à l\'amélioration des guidelines']),
      benefits: JSON.stringify(['Soutien psychologique disponible', 'Pauses régulières', 'Prime de contenu sensible', 'Formation continue']),
      companyId: createdCompanies[2].id,
    },

    // === DEVELOPMENT / IT ===
    {
      title: 'Développeur(euse) Full Stack JavaScript',
      description: 'Rejoignez notre équipe technique pour développer des applications web modernes pour nos clients français. Stack: React, Node.js, TypeScript.',
      category: 'technology',
      location: 'Antananarivo, Madagascar',
      locationType: 'hybrid',
      employmentType: 'full-time',
      experienceLevel: 'mid',
      salaryMin: 1500000,
      salaryMax: 2500000,
      salaryCurrency: 'MGA',
      salaryPeriod: 'monthly',
      requirements: JSON.stringify(['2+ ans en développement web', 'React.js et Node.js', 'TypeScript', 'Git et méthodologies Agile']),
      responsibilities: JSON.stringify(['Développer des fonctionnalités front et back', 'Participer aux code reviews', 'Collaborer avec les équipes en France', 'Maintenir la documentation']),
      benefits: JSON.stringify(['Télétravail partiel', 'Équipement fourni', 'Formation technique', 'Projets internationaux']),
      companyId: createdCompanies[3].id,
    },
    {
      title: 'Développeur(euse) Mobile Flutter',
      description: 'Créez des applications mobiles cross-platform avec Flutter/Dart pour des startups françaises innovantes.',
      category: 'technology',
      location: 'Antananarivo, Madagascar',
      locationType: 'remote',
      employmentType: 'full-time',
      experienceLevel: 'mid',
      salaryMin: 1800000,
      salaryMax: 3000000,
      salaryCurrency: 'MGA',
      salaryPeriod: 'monthly',
      requirements: JSON.stringify(['2+ ans en développement mobile', 'Flutter/Dart', 'Publication sur App Store et Play Store', 'API REST']),
      responsibilities: JSON.stringify(['Développer des apps iOS et Android', 'Intégrer les APIs backend', 'Optimiser les performances', 'Tester et debugger']),
      benefits: JSON.stringify(['100% remote', 'Salaire compétitif', 'Projets variés', 'Évolution technique']),
      companyId: createdCompanies[3].id,
    },
    {
      title: 'Développeur(euse) WordPress / PHP',
      description: 'Créez et maintenez des sites WordPress pour des PME françaises. De la création de thèmes aux plugins personnalisés.',
      category: 'technology',
      location: 'Antananarivo, Madagascar',
      locationType: 'hybrid',
      employmentType: 'full-time',
      experienceLevel: 'entry',
      salaryMin: 800000,
      salaryMax: 1400000,
      salaryCurrency: 'MGA',
      salaryPeriod: 'monthly',
      requirements: JSON.stringify(['1+ an avec WordPress', 'PHP, HTML, CSS, JavaScript', 'Création de thèmes/plugins', 'Notions SEO']),
      responsibilities: JSON.stringify(['Développer des sites WordPress', 'Créer des thèmes sur mesure', 'Maintenir et sécuriser les sites', 'Former les clients à l\'utilisation']),
      benefits: JSON.stringify(['Variété de projets', 'Formation WordPress avancée', 'Télétravail 2j/sem', 'Ambiance startup']),
      companyId: createdCompanies[4].id,
    },
    {
      title: 'Intégrateur(trice) Web',
      description: 'Transformez les maquettes en sites web pixel-perfect. Vous travaillez en étroite collaboration avec les designers.',
      category: 'technology',
      location: 'Antananarivo, Madagascar',
      locationType: 'onsite',
      employmentType: 'full-time',
      experienceLevel: 'entry',
      salaryMin: 600000,
      salaryMax: 1000000,
      salaryCurrency: 'MGA',
      salaryPeriod: 'monthly',
      requirements: JSON.stringify(['Maîtrise HTML5, CSS3, JavaScript', 'Responsive design', 'Connaissance de Figma/XD', 'Sens du détail']),
      responsibilities: JSON.stringify(['Intégrer les maquettes en code', 'Assurer la compatibilité navigateurs', 'Optimiser pour le mobile', 'Collaborer avec les designers']),
      benefits: JSON.stringify(['Équipe créative', 'Projets design variés', 'Formation continue', 'Évolution vers développeur']),
      companyId: createdCompanies[4].id,
    },

    // === DESIGN / CREATIVE ===
    {
      title: 'Graphiste / Designer UI',
      description: 'Créez des visuels impactants et des interfaces utilisateur modernes pour nos clients français et internationaux.',
      category: 'design',
      location: 'Antananarivo, Madagascar',
      locationType: 'hybrid',
      employmentType: 'full-time',
      experienceLevel: 'mid',
      salaryMin: 1000000,
      salaryMax: 1600000,
      salaryCurrency: 'MGA',
      salaryPeriod: 'monthly',
      requirements: JSON.stringify(['2+ ans en design graphique', 'Suite Adobe (Photoshop, Illustrator)', 'Figma pour l\'UI', 'Portfolio créatif']),
      responsibilities: JSON.stringify(['Créer des identités visuelles', 'Designer des interfaces web/mobile', 'Produire des supports marketing', 'Respecter les briefs créatifs']),
      benefits: JSON.stringify(['Licence Adobe fournie', 'Projets internationaux', 'Direction artistique', 'Télétravail partiel']),
      companyId: createdCompanies[4].id,
    },
    {
      title: 'Motion Designer',
      description: 'Créez des animations et vidéos motion design pour des marques françaises. Du motion graphics à l\'animation 2D.',
      category: 'design',
      location: 'Antananarivo, Madagascar',
      locationType: 'remote',
      employmentType: 'full-time',
      experienceLevel: 'mid',
      salaryMin: 1200000,
      salaryMax: 2000000,
      salaryCurrency: 'MGA',
      salaryPeriod: 'monthly',
      requirements: JSON.stringify(['2+ ans en motion design', 'After Effects, Premiere Pro', 'Animation 2D (Lottie, etc.)', 'Sens du storytelling']),
      responsibilities: JSON.stringify(['Créer des animations pour le web', 'Produire des vidéos explicatives', 'Animer des logos et éléments UI', 'Collaborer avec les équipes marketing']),
      benefits: JSON.stringify(['Remote complet', 'Logiciels fournis', 'Projets créatifs variés', 'Clients grandes marques']),
      companyId: createdCompanies[6].id,
    },

    // === MARKETING / DIGITAL ===
    {
      title: 'Community Manager',
      description: 'Gérez les réseaux sociaux de marques françaises. De la création de contenu à l\'engagement communautaire.',
      category: 'marketing',
      location: 'Antananarivo, Madagascar',
      locationType: 'hybrid',
      employmentType: 'full-time',
      experienceLevel: 'entry',
      salaryMin: 700000,
      salaryMax: 1100000,
      salaryCurrency: 'MGA',
      salaryPeriod: 'monthly',
      requirements: JSON.stringify(['Français impeccable', 'Connaissance approfondie des réseaux sociaux', 'Créativité rédactionnelle', 'Maîtrise des outils de planification']),
      responsibilities: JSON.stringify(['Créer et publier du contenu', 'Animer les communautés', 'Répondre aux messages et commentaires', 'Analyser les performances']),
      benefits: JSON.stringify(['Variété de clients', 'Formation social media', 'Ambiance créative', 'Veille tendances']),
      companyId: createdCompanies[4].id,
    },
    {
      title: 'Rédacteur(trice) Web SEO',
      description: 'Rédigez des contenus web optimisés SEO pour des sites français. Articles de blog, pages produits, landing pages.',
      category: 'marketing',
      location: 'Antananarivo, Madagascar',
      locationType: 'remote',
      employmentType: 'full-time',
      experienceLevel: 'entry',
      salaryMin: 600000,
      salaryMax: 1000000,
      salaryCurrency: 'MGA',
      salaryPeriod: 'monthly',
      requirements: JSON.stringify(['Français natif ou niveau C2', 'Connaissance des techniques SEO', 'Capacité de recherche', 'Adaptabilité tonale']),
      responsibilities: JSON.stringify(['Rédiger des articles optimisés SEO', 'Créer des fiches produits', 'Respecter les briefs rédactionnels', 'Livrer dans les délais']),
      benefits: JSON.stringify(['Travail 100% remote', 'Diversité des sujets', 'Formation SEO', 'Progression rapide']),
      companyId: createdCompanies[6].id,
    },
    {
      title: 'Chargé(e) de Traffic Digital',
      description: 'Gérez les campagnes publicitaires Google Ads et Meta Ads pour des annonceurs français. Poste technique et analytique.',
      category: 'marketing',
      location: 'Antananarivo, Madagascar',
      locationType: 'hybrid',
      employmentType: 'full-time',
      experienceLevel: 'mid',
      salaryMin: 1000000,
      salaryMax: 1600000,
      salaryCurrency: 'MGA',
      salaryPeriod: 'monthly',
      requirements: JSON.stringify(['1+ an en gestion de campagnes', 'Google Ads et Meta Ads', 'Maîtrise de Google Analytics', 'Esprit analytique']),
      responsibilities: JSON.stringify(['Créer et optimiser les campagnes', 'Analyser les performances', 'Gérer les budgets publicitaires', 'Produire des reportings']),
      benefits: JSON.stringify(['Certifications Google offertes', 'Budgets significatifs', 'Évolution vers consultant', 'Télétravail partiel']),
      companyId: createdCompanies[6].id,
    },

    // === ACCOUNTING / FINANCE ===
    {
      title: 'Comptable Junior',
      description: 'Intégrez un cabinet comptable moderne et traitez la comptabilité de PME françaises. Formation au logiciel et aux normes françaises assurée.',
      category: 'finance',
      location: 'Antananarivo, Madagascar',
      locationType: 'onsite',
      employmentType: 'full-time',
      experienceLevel: 'entry',
      salaryMin: 800000,
      salaryMax: 1200000,
      salaryCurrency: 'MGA',
      salaryPeriod: 'monthly',
      requirements: JSON.stringify(['Bac+2/3 en comptabilité', 'Notions de comptabilité française', 'Maîtrise d\'Excel', 'Rigueur et organisation']),
      responsibilities: JSON.stringify(['Saisir les écritures comptables', 'Réaliser les rapprochements bancaires', 'Préparer les déclarations TVA', 'Assister les comptables seniors']),
      benefits: JSON.stringify(['Formation aux normes françaises', 'Logiciel comptable moderne', 'Évolution possible', '13ème mois']),
      companyId: createdCompanies[5].id,
    },
    {
      title: 'Gestionnaire de Paie',
      description: 'Établissez les bulletins de paie pour des entreprises françaises. Connaissance du droit social français requise ou formation assurée.',
      category: 'finance',
      location: 'Antananarivo, Madagascar',
      locationType: 'onsite',
      employmentType: 'full-time',
      experienceLevel: 'mid',
      salaryMin: 1000000,
      salaryMax: 1500000,
      salaryCurrency: 'MGA',
      salaryPeriod: 'monthly',
      requirements: JSON.stringify(['2+ ans en paie', 'Connaissance des conventions collectives françaises', 'Logiciel de paie (Sage, Silae...)', 'Rigueur absolue']),
      responsibilities: JSON.stringify(['Établir les bulletins de paie', 'Gérer les déclarations sociales', 'Traiter les entrées/sorties', 'Répondre aux salariés']),
      benefits: JSON.stringify(['Spécialisation paie française', 'Prime de technicité', 'Mutuelle complète', 'Stabilité de l\'emploi']),
      companyId: createdCompanies[5].id,
    },
    {
      title: 'Assistant(e) Administratif(ve)',
      description: 'Assistez la direction et les équipes dans les tâches administratives quotidiennes. Poste polyvalent et formateur.',
      category: 'other',
      location: 'Antananarivo, Madagascar',
      locationType: 'onsite',
      employmentType: 'full-time',
      experienceLevel: 'entry',
      salaryMin: 500000,
      salaryMax: 750000,
      salaryCurrency: 'MGA',
      salaryPeriod: 'monthly',
      requirements: JSON.stringify(['Bac+2 minimum', 'Français courant', 'Maîtrise du Pack Office', 'Organisation et rigueur']),
      responsibilities: JSON.stringify(['Gérer le courrier et les emails', 'Organiser les réunions', 'Classer et archiver les documents', 'Assister la direction']),
      benefits: JSON.stringify(['Polyvalence du poste', 'Environnement international', 'Formation bureautique', 'Évolution administrative']),
      companyId: createdCompanies[1].id,
    },

    // === TECHNICAL / SPECIALIZED ===
    {
      title: 'Testeur(euse) QA',
      description: 'Assurez la qualité des applications développées pour nos clients français. Tests manuels et automatisés.',
      category: 'technology',
      location: 'Antananarivo, Madagascar',
      locationType: 'hybrid',
      employmentType: 'full-time',
      experienceLevel: 'entry',
      salaryMin: 700000,
      salaryMax: 1100000,
      salaryCurrency: 'MGA',
      salaryPeriod: 'monthly',
      requirements: JSON.stringify(['Connaissance des tests logiciels', 'Rigueur et sens du détail', 'Capacité de rédaction', 'Notions de développement appréciées']),
      responsibilities: JSON.stringify(['Exécuter les cas de test', 'Rédiger les rapports de bugs', 'Participer aux sprints Agile', 'Proposer des améliorations']),
      benefits: JSON.stringify(['Formation QA', 'Évolution vers QA automation', 'Projets variés', 'Méthodologies modernes']),
      companyId: createdCompanies[3].id,
    },
    {
      title: 'Transcripteur(trice) Audio',
      description: 'Transcrivez des fichiers audio et vidéo en français. Réunions, interviews, podcasts... Précision et rapidité requises.',
      category: 'other',
      location: 'Antananarivo, Madagascar',
      locationType: 'remote',
      employmentType: 'part-time',
      experienceLevel: 'entry',
      salaryMin: 300000,
      salaryMax: 500000,
      salaryCurrency: 'MGA',
      salaryPeriod: 'monthly',
      requirements: JSON.stringify(['Français parfait', 'Frappe rapide (60+ mots/min)', 'Bonne oreille', 'Équipement audio correct']),
      responsibilities: JSON.stringify(['Transcrire les fichiers audio', 'Respecter les formats demandés', 'Livrer dans les délais', 'Relire et corriger']),
      benefits: JSON.stringify(['Horaires flexibles', 'Travail à domicile', 'Paiement à la minute', 'Volume régulier']),
      companyId: createdCompanies[2].id,
    },
    {
      title: 'Traducteur(trice) Français-Anglais',
      description: 'Traduisez des documents, sites web et contenus marketing du français vers l\'anglais et vice-versa.',
      category: 'other',
      location: 'Antananarivo, Madagascar',
      locationType: 'remote',
      employmentType: 'freelance',
      experienceLevel: 'mid',
      salaryMin: 800000,
      salaryMax: 1500000,
      salaryCurrency: 'MGA',
      salaryPeriod: 'monthly',
      requirements: JSON.stringify(['Français et anglais niveau natif', 'Expérience en traduction professionnelle', 'Spécialisation (juridique, technique, marketing)', 'Outils de TAO appréciés']),
      responsibilities: JSON.stringify(['Traduire les documents assignés', 'Relire et réviser', 'Respecter la terminologie client', 'Livrer dans les délais']),
      benefits: JSON.stringify(['Volume régulier', 'Tarif compétitif', 'Clients fidèles', 'Flexibilité totale']),
      companyId: createdCompanies[6].id,
    },

    // === MORE SENIOR / SPECIALIZED ROLES ===
    {
      title: 'Chef de Projet IT Offshore',
      description: 'Coordonnez les projets de développement entre les équipes en France et à Madagascar. Rôle clé de liaison et de suivi.',
      category: 'product',
      location: 'Antananarivo, Madagascar',
      locationType: 'hybrid',
      employmentType: 'full-time',
      experienceLevel: 'senior',
      salaryMin: 2500000,
      salaryMax: 4000000,
      salaryCurrency: 'MGA',
      salaryPeriod: 'monthly',
      requirements: JSON.stringify(['5+ ans en gestion de projet IT', 'Expérience offshore/nearshore', 'Méthodologie Agile/Scrum', 'Excellent français et anglais']),
      responsibilities: JSON.stringify(['Coordonner les équipes France/Madagascar', 'Planifier et suivre les sprints', 'Gérer la relation client', 'Assurer la qualité des livrables']),
      benefits: JSON.stringify(['Salaire attractif', 'Responsabilités importantes', 'Voyages en France possibles', 'Management d\'équipe']),
      companyId: createdCompanies[3].id,
    },
    {
      title: 'Lead Developer Backend',
      description: 'Dirigez une équipe de développeurs backend et architecturez nos solutions techniques. Stack: Node.js, Python, PostgreSQL.',
      category: 'technology',
      location: 'Antananarivo, Madagascar',
      locationType: 'hybrid',
      employmentType: 'full-time',
      experienceLevel: 'lead',
      salaryMin: 3000000,
      salaryMax: 5000000,
      salaryCurrency: 'MGA',
      salaryPeriod: 'monthly',
      requirements: JSON.stringify(['5+ ans en développement backend', 'Node.js ou Python expert', 'Architecture microservices', 'Leadership technique']),
      responsibilities: JSON.stringify(['Architecturer les solutions', 'Encadrer l\'équipe technique', 'Garantir la qualité du code', 'Définir les standards']),
      benefits: JSON.stringify(['Package compétitif', 'Leadership reconnu', 'Formation continue', 'Projets stimulants']),
      companyId: createdCompanies[3].id,
    },
  ]

  // Create all jobs
  for (const job of jobs) {
    try {
      await prisma.job.create({
        data: {
          ...job,
          status: 'OPEN',
        }
      })
      console.log('✅ Created job:', job.title)
    } catch (error) {
      console.log('⚠️ Job already exists or error:', job.title)
    }
  }

  console.log(`\n🎉 Successfully seeded ${jobs.length} Madagascar remote jobs!`)
  console.log('📍 Companies: French BPOs and digital agencies outsourcing to Madagascar')
  console.log('💼 Jobs: Customer service, data entry, development, design, marketing, accounting')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
